### ISSUE TITLE
Reverse smelting and 2 coin changes

### ISSUE THREAD

**Issue by BinLox** [Darkhax-Minecraft/Coins#10]
Please add the ability (maybe optional?) to smelt single coins back into their original objects - iron, gold, diamond.

Please remove copper and platinum and change them to emerald and netherite, thereby changing the crafting route from
Copper, Iron, Gold, Platinum, Diamond
to
Iron, Gold, Diamond, Emerald, Netherite

Thank you!!

**Comment by Darkhax** [comment]
Hello, 

These changes would have some serious consequences for players and how they progress through the game. What you are suggesting would allow conversion/transmutation of resources.  If a player has 9 emeralds they could make a netherite ingot, or 81 diamonds, or 729 gold ingots, or 6561 iron ingots. And emeralds are by far one of the easiest materials to obtain. As for using copper/platinum materials instead of emerald/netherite, this was done intentionally to make the mod similar to currency systems in other games. Mojang are also adding copper in 1.17 and once that happens copper would make more sense.

You're more than welcome to make these crafting changes yourself using something like CraftTweaker or data packs though.
